import { defineConfig } from "vite";
import react from "@vitejs/plugin-react";
import { fileURLToPath } from "url";
import fs from "fs";
import path from "path";

// Load dev certs if available (generated by setup-certs.cmd)
const certPath = path.resolve(__dirname, "../../dev-certs/certs");
const httpsConfig = fs.existsSync(path.join(certPath, "localhost.pem"))
  ? {
      key: fs.readFileSync(path.join(certPath, "localhost-key.pem")),
      cert: fs.readFileSync(path.join(certPath, "localhost.pem")),
    }
  : undefined;

export default defineConfig({
  plugins: [react()],
  resolve: {
    alias: {
      "@": fileURLToPath(new URL("./src", import.meta.url)),
    },
  },
  server: {
    port: 3000,
    https: httpsConfig,
    proxy: {
      "/api/patients": {
        target: process.env.VITE_PATIENT_API_URL ?? "https://localhost:5002",
        changeOrigin: true,
        secure: false,
        rewrite: (urlPath) => urlPath.replace(/^\/api\/patients/, ""),
      },
      "/api/appointments": {
        target: process.env.VITE_APPOINTMENT_API_URL ?? "https://localhost:5003",
        changeOrigin: true,
        secure: false,
        rewrite: (urlPath) => urlPath.replace(/^\/api\/appointments/, ""),
      },
      "/api/medicalrecords": {
        target: process.env.VITE_MEDICALRECORDS_API_URL ?? "https://localhost:5004",
        changeOrigin: true,
        secure: false,
        rewrite: (urlPath) => urlPath.replace(/^\/api\/medicalrecords/, ""),
      },
    },
  },
});
