import { defineConfig } from "vite";
import react from "@vitejs/plugin-react";
import { fileURLToPath } from "url";
import fs from "fs";
import path from "path";

// Load dev certs if available (generated by setup-certs.cmd)
const certPath = path.resolve(__dirname, "../../dev-certs/certs");
const httpsConfig = fs.existsSync(path.join(certPath, "localhost.pem"))
  ? {
      key: fs.readFileSync(path.join(certPath, "localhost-key.pem")),
      cert: fs.readFileSync(path.join(certPath, "localhost.pem")),
    }
  : undefined;

export default defineConfig({
  plugins: [react()],
  resolve: {
    alias: {
      "@": fileURLToPath(new URL("./src", import.meta.url)),
    },
  },
  build: {
    chunkSizeWarningLimit: 500,
    rollupOptions: {
      output: {
        manualChunks(id) {
          if (id.includes("node_modules")) {
            if (id.includes("react-dom") || id.includes("react-router-dom") || id.match(/\/react\//) || id.includes("react-redux")) {
              return "vendor-react";
            }
            if (id.includes("@reduxjs/toolkit")) {
              return "vendor-redux";
            }
            if (id.includes("@radix-ui") || id.includes("class-variance-authority") || id.includes("clsx") || id.includes("tailwind-merge")) {
              return "vendor-ui";
            }
            if (id.includes("recharts")) {
              return "vendor-charts";
            }
            if (id.includes("@schedule-x")) {
              return "vendor-calendar";
            }
            if (id.includes("@microsoft/signalr")) {
              return "vendor-signalr";
            }
            if (id.includes("oidc-client-ts") || id.includes("react-oidc-context")) {
              return "vendor-auth";
            }
          }
        },
      },
    },
  },
  server: {
    port: parseInt(process.env.PORT || "3000"),
    https: httpsConfig,
    proxy: {
      "/api/patients": {
        target: process.env.VITE_PATIENT_API_URL ?? "https://localhost:5002",
        changeOrigin: true,
        secure: false,
        rewrite: (urlPath) => urlPath.replace(/^\/api\/patients/, ""),
      },
      "/api/appointments": {
        target: process.env.VITE_APPOINTMENT_API_URL ?? "https://localhost:5003",
        changeOrigin: true,
        secure: false,
        rewrite: (urlPath) => urlPath.replace(/^\/api\/appointments/, ""),
      },
      "/api/medicalrecords": {
        target: process.env.VITE_MEDICALRECORDS_API_URL ?? "https://localhost:5004",
        changeOrigin: true,
        secure: false,
        rewrite: (urlPath) => urlPath.replace(/^\/api\/medicalrecords/, ""),
      },
    },
  },
});
